### ISSUE TITLE
Testing multiple files

### ISSUE THREAD

**Issue by matejzero** [breml/logstash-config#2]
I'm trying to use a docker image with `ls-config-check` to check all my config files in a single job, as I have all of them in a single folder and would like to avoid adding another script to run a for loop inside a container. 

I'm using a command `ls-config-check *.conf`.

Is that suppose to work or not? If not, would you willing to implement that in your example? I have 0 knowledge of Go, but I would make a Dockerfile in exchange:)

**Comment by breml** [comment]
Hi @matejzero
`ls-config-check` currently has a very primitive cli interface, which unfortunately does not work with multiple files at the moment. The cli does really need some love. Maybe I find some time to create a better solution, not promises though.

**Comment by matejzero** [comment]
I saw it's really primitive, more of an example, as you said in the README.

I managed to work around it with a for loop, but if you find some time to give it some love, I would be happy to use it:)

**Comment by breml** [comment]
I keep it open as an reminder.
